### ISSUE TITLE
make test receive that error!

### ISSUE THREAD

**Issue by moruoxian** [alibaba/async_simple#92] opened 2022-04-13 03:15 UTC
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

root@win10:/home/Project/async_simple/build# make test
Running tests...
Test project /home/Project/async_simple/build
    Start 1: run_async_simple_test
1/5 Test #1: run_async_simple_test ............   Passed    2.73 sec
    Start 2: run_async_simple_util_test
2/5 Test #2: run_async_simple_util_test .......   Passed    0.02 sec
    Start 3: run_async_simple_coro_test
3/5 Test #3: run_async_simple_coro_test .......***Failed   37.21 sec
    Start 4: run_async_simple_executor_test
4/5 Test #4: run_async_simple_executor_test ...   Passed    1.07 sec
    Start 5: run_async_simple_uthread_test
5/5 Test #5: run_async_simple_uthread_test ....   Passed    3.95 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =  44.99 sec

The following tests FAILED:
          3 - run_async_simple_coro_test (Failed)
Errors while running CTest

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by moruoxian** [comment] 2022-04-13 03:18
ubuntu 20.04
Linux win10 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04)

**Comment by qicosmos** [comment] 2022-04-13 07:27
I tested on my ububtu20.04, gcc11.1

```
Test project /home/ubuntu/code/async_simple/build
    Start 1: run_async_simple_test
1/5 Test #1: run_async_simple_test ............   Passed    1.21 sec
    Start 2: run_async_simple_util_test
2/5 Test #2: run_async_simple_util_test .......   Passed    0.00 sec
    Start 3: run_async_simple_coro_test
3/5 Test #3: run_async_simple_coro_test .......   Passed   12.81 sec
    Start 4: run_async_simple_executor_test
4/5 Test #4: run_async_simple_executor_test ...   Passed    0.00 sec
    Start 5: run_async_simple_uthread_test
5/5 Test #5: run_async_simple_uthread_test ....   Passed    1.66 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =  15.71 sec
```
It's ok, i guess the problem is the gcc version, try to upgrade to gcc11.

**Comment by ChuanqiXu9** [comment] 2022-04-15 05:00
gcc 10.3 is one of  the suggested compiler version. It runs in our CI system.
The problem might be related to `CMAKE_BUILD_TYPE`. I've confirmed that the async_simple_coro_test would crash with gcc10.3 + CMAKE_BUILD_TYPE=Debug. The CI system only tests gcc10.3 with release version.
@moruoxian could you please try to test it under clang?

**Comment by ChuanqiXu9** [comment] 2022-04-25 03:27
This one should be addressed in https://github.com/alibaba/async_simple/commit/a0d9b01df5beb2b01a9b68808c93fea49dcb22b8, thanks for raising the issue.

**Closed by ChuanqiXu9** 2022-04-25 03:27 UTC
